// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwc5DhfWg2W1mCQY0aXl1kJ6kU_S5gvbs',
    appId: '1:755876834223:web:94cecbb8e06f50d9521d5a',
    messagingSenderId: '755876834223',
    projectId: 'omnia-acm',
    authDomain: 'omnia-acm.firebaseapp.com',
    storageBucket: 'omnia-acm.appspot.com',
    measurementId: 'G-GHS60M5BX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUsh9vYt1zcs3oIgozKIV4LlSgCKp5F40',
    appId: '1:755876834223:android:1cde954047b80d14521d5a',
    messagingSenderId: '755876834223',
    projectId: 'omnia-acm',
    storageBucket: 'omnia-acm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkUCC9PCnoqEeXrcLsysZO-Y4xqN9XuW0',
    appId: '1:755876834223:ios:c67a585ed77d1bf1521d5a',
    messagingSenderId: '755876834223',
    projectId: 'omnia-acm',
    storageBucket: 'omnia-acm.appspot.com',
    iosBundleId: 'com.example.omnia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkUCC9PCnoqEeXrcLsysZO-Y4xqN9XuW0',
    appId: '1:755876834223:ios:c67a585ed77d1bf1521d5a',
    messagingSenderId: '755876834223',
    projectId: 'omnia-acm',
    storageBucket: 'omnia-acm.appspot.com',
    iosBundleId: 'com.example.omnia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwc5DhfWg2W1mCQY0aXl1kJ6kU_S5gvbs',
    appId: '1:755876834223:web:ba5651cbe3b60378521d5a',
    messagingSenderId: '755876834223',
    projectId: 'omnia-acm',
    authDomain: 'omnia-acm.firebaseapp.com',
    storageBucket: 'omnia-acm.appspot.com',
    measurementId: 'G-6TLY42PPME',
  );
}

